### ISSUE TITLE
Improve support of eslint-plugin-import

### ISSUE THREAD

**Issue by mgtitimoli** [entwicklerstube/babel-plugin-root-import#57]
Hi there!

First of all, I would like to say thank you for your amazing work!

I came across to your project from [this tweet](https://twitter.com/jevakallio/status/796008962592215040), and while I was reading the docs, there was something that grab my attention, and is basically that you suggest to disable [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import)... So at that moment I thought "_it must be some other way to deal with this_", and I guess there is one:
- [eslint-plugin-import resolvers](https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/README.md)

If you have some time, don't you mind to have a look to it? I was thinking that maybe we could provide a custom resolver, so it would be just a matter to include it from `babel-root-import/eslint-plugin-import-resolver`, what do you think?

Thanks!

**Comment by adrianmcli** [comment]
@mgtitimoli any luck on this? I am trying to get eslint-plugin-import to work as well and I'm having issues.

**Comment by layerssss** [comment]
Thanks for pointing me to the right direction @mgtitimoli , I've implemented a fairly compatible resolver as gist: https://gist.github.com/layerssss/68eb1db9a43a5cf3325fbe25d62bad12 @adrianmcli

**Comment by divyanshu013** [comment]
Hi, I've tried the eslint plugin mentioned in the readme. However, my eslint still shows an error for imports.

**Comment by raphaellopes** [comment]
@divyanshu013 I'm not sure if is your case, but I had problems with my eslint, and after config the `rootPathPrefix` and `rootPathSuffix` in my `.eslintrc`, it fixed for me:

```
{
  "extends": "airbnb",
  "rules": {},
  "settings": {
    "import/resolver": {
      "babel-plugin-root-import": {
        "rootPathPrefix": "~",
        "rootPathSuffix": "src"
      }
    }
  }
}
```
